name: cloud_firestore_api
description: A clean and efficient approach to dealing with data from Firestore.
version: 0.1.0
homepage: https://github.com/ultrawideturbodev/cloud_firestore_api

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  flutter:
    sdk: flutter
  turbo_response: ^0.2.0

dev_dependencies:
  fake_cloud_firestore: ^2.5.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
